name: "Staging Checks"

on:
  push:
    branches: "staging/*"
  pull_request:
    branches: "staging/*"

jobs:

  vet:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: "Go Vet"
        run: "go vet ./..."

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: "Go Test"
        run: "go test ./..."

  staticcheck:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - uses: actions/checkout@v3
    - name: "staticcheck"
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
        install-go: false
